# Mostly duplicated from
# https://github.com/pytorch/vision/blob/master/.travis.yml

language: python
sudo: required
dist: xenial
cache:
  pip: true
  directories:
    - $HOME/miniconda

matrix:
  include:
    - env: LINT_CHECK
      python: "3.6"
      install: pip install flake8
      script: flake8

    - python: "3.5"
    - python: "3.5"
      env: IMAGE_BACKEND=Pillow-SIMD

    - python: "3.6"
    - python: "3.6"
      env: IMAGE_BACKEND=Pillow-SIMD

    - python: "3.7"
    - python: "3.7"
      env: IMAGE_BACKEND=Pillow-SIMD

install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - if [[ -d $HOME/miniconda ]]; then
      bash miniconda.sh -b -p $HOME/miniconda -u
    else
      bash miniconda.sh -b -p $HOME/miniconda
    fi
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pytorch scipy -c pytorch
  - conda install -c conda-forge ffmpeg av lintel
  - source activate test-environment
  - python setup.py install
  - pip install --upgrade pytest
  - if [[ "$IMAGE_BACKEND" == "Pillow-SIMD" ]]; then
      pip uninstall -y pillow && CC="cc -march=native" pip install --force-reinstall pillow-simd;
    fi
  - pushd tests/data/media
      ./gen_test_media.sh
    popd

script:
- make test

after_success:
- coverage combine
- coverage report
- codecov
